name: CI

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_sqlite, tokenizer
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run PHPStan
        run: composer phpstan

      - name: Run Coding Standard
        run: composer phpcs

      - name: Run Tests
        run: vendor/bin/tester -C . tests -j=1
